language: node_js

node_js:
  - "8"
dist: trusty
addons:
  chrome: stable
before_script:
  - npm install -g snyk
  - npm install -g codecov

script:
  - snyk test
  - npm test -- --coverage

after_script:
  - codecov

after_success:
  - snyk monitor

notifications:
  email: false